import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className='h-14 bg-[#D2D2D2] bg-opacity-[40%] flex justify-start items-center'>
        <h4 className='font-bold text-md ml-[50px]'>Akun / Login</h4>
      </div>
      {children}
    </>
  );
}
