import type { Metadata } from 'next';
import Sidebar from './components/Sidebar';
import { NextUILibProvider } from '../context/NextUILibProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <NextUILibProvider>
      <Sidebar className='col-span-1' />
      <main className='col-span-4'>{children}</main>
    </NextUILibProvider>
  );
}
