import { options } from '@/app/api/auth/[...nextauth]/options';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import Image from 'next/image';
import Link from 'next/link';
import { HiOutlineShoppingBag } from 'react-icons/hi2';
import {
  IoIosArrowForward,
  IoMdSettings,
  IoIosLock,
  IoIosLogOut,
  IoIosPin,
} from 'react-icons/io';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function ProfileLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  return (
    <main className='grid grid-cols-12 mt-10 gap-4'>
      <section className='col-start-2 col-end-5 px-5 border-r-1 h-full'>
        <div className='flex flex-col gap-6'>
          <div className='flex flex-col justify-center items-center align-middle'>
            <h3 className='text-2xl font-semibold'>My Profile</h3>
            <div className='relative w-24 h-24 rounded-full bg-blue-50'>
              <Image
                className='rounded-full'
                alt='alt'
                src={session?.user.image ?? ''}
                fill
              />
            </div>
            <h4 className='text-lg font-semibold'>{session?.user.name}</h4>
            <p>{session?.user.email}</p>
          </div>
          <div className='grid grid-flow-row gap-3'>
            <Link href={'/my-orders'}>
              <div className='flex justify-between items-center'>
                <div className='flex gap-3 items-center'>
                  <div className='rounded-md p-3 bg-[#E0E0E0]'>
                    <HiOutlineShoppingBag size={35} />
                  </div>
                  <h4 className='text-lg font-semibold'>Pesanan Saya</h4>
                </div>
                <IoIosArrowForward />
              </div>
            </Link>
            <Link href={'/addresses'}>
              <div className='flex justify-between items-center'>
                <div className='flex gap-3 items-center'>
                  <div className='rounded-md p-3 bg-[#E0E0E0]'>
                    <IoIosPin size={35} />
                  </div>
                  <h4 className='text-lg font-semibold'>Daftar Alamat</h4>
                </div>
                <IoIosArrowForward />
              </div>
            </Link>
            <Link href={'/settings'}>
              <div className='flex justify-between items-center'>
                <div className='flex gap-3 items-center'>
                  <div className='rounded-md p-3 bg-[#E0E0E0]'>
                    <IoMdSettings size={35} />
                  </div>
                  <h4 className='text-lg font-semibold'>Edit Profile</h4>
                </div>
                <IoIosArrowForward />
              </div>
            </Link>
            <Link href={'/settings/change-password'}>
              <div className='flex justify-between items-center'>
                <div className='flex gap-3 items-center'>
                  <div className='rounded-md p-3 bg-[#E0E0E0]'>
                    <IoIosLock size={35} />
                  </div>
                  <h4 className='text-lg font-semibold'>Ganti Kata Sandi</h4>
                </div>
                <IoIosArrowForward />
              </div>
            </Link>
            <Link href={'/api/auth/signout'}>
              <div className='flex justify-between items-center'>
                <div className='flex gap-3 items-center'>
                  <div className='rounded-md p-3 bg-[#E0E0E0]'>
                    <IoIosLogOut size={35} />
                  </div>
                  <h4 className='text-lg font-semibold'>Logout</h4>
                </div>
                <IoIosArrowForward />
              </div>
            </Link>
          </div>
        </div>
      </section>
      <div className='col-start-5 col-end-12'>{children}</div>
    </main>
  );
}
