import type { Metadata } from 'next';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import { NextUILibProvider } from '../context/NextUILibProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function CustomerLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      <NextUILibProvider>{children}</NextUILibProvider>
      <Footer />
    </>
  );
}
