import type { Metadata } from 'next';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import { NextUILibProvider } from '../context/NextUILibProvider';
import { Session, getServerSession } from 'next-auth';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function CustomerLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: {
    session: Session;
  };
}) {
  return (
    <>
      <Navbar />
      <NextUILibProvider>{children}</NextUILibProvider>
      <Footer />
    </>
  );
}
