import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthProvider from '@/app/context/AuthProvider';
import RQProvider from '@/app/context/RQProvider';
import { NextUILibProvider } from './context/NextUILibProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <RQProvider>
            <NextUILibProvider>{children}</NextUILibProvider>
          </RQProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
