import type { Metadata } from 'next';
import NavTabs from './components/NavTabs';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function CustomerLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className='sm:w-7/12 sm:m-auto flex flex-col gap-5'>
      <NavTabs />
      {children}
    </main>
  );
}
